apiVersion: v1
kind: Service
metadata:
  labels:
    app: testdb
  name: testdb
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    deploymentconfig: testdb
  sessionAffinity: None
  type: ClusterIP
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: testdb
  name: testdb-lb-service
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  ports:
  - nodePort: 30231
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    deploymentconfig: testdb
  sessionAffinity: None
  type: LoadBalancer
status: {}

